# Generated by Django 4.0.3 on 2024-02-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saleperson',
            new_name='Salesperson',
        ),
    ]
