# Generated by Django 4.0.3 on 2024-02-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
